#!/usr/bin/env bash

# Emacs: This is a -*- Shell-script -*-.

# This file is part of GC-LPI. 

# GC-LPI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# GC-LPI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with GC-LPI.  If not, see <http://www.gnu.org/licenses/>.


# This script sets up Papercut on a GNU/Linux machine.
# Note: This script needs to be run by the root user as
#       the script will create a new user and add a symbolic
#       file inside /usr/bin.

# Zachary John Susag
# Department of Computer Science
# Grinnell College
# susagzac@grinnell.edu

# Created: July 6, 2017
# Last revised: March 9, 2018

# Check to see if the script is run as root.
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root in order to work properly." 
   exit 1
fi

# Create the papercut user and group.
echo "Creating the papercut user and group."
useradd -rU papercut

# Echo the newly created UID and GID.
papercut_uid="$(id -u papercut)"
papercut_gid="$(id -G papercut)"
echo "UID: $papercut_uid"
echo "GID: $papercut_gid"

# Create the local directory in which PaperCut files will be stored.
mkdir /opt/papercut

# Prompt the user to enter in his/her/their username in order
# to connect to Grinnell College's Samba server.
echo "Retrieving and copying PaperCut source files "
echo -n "Enter in your Grinnell College username followed by [ENTER]: "
read username

# Connect to Grinnell College's print server and download the 'linux'
# directory.
smbclient \\\\print\\PCClient -U $username -W Grin -c 'prompt OFF;recurse ON;cd 'linux';lcd '/opt/papercut';mget *'

# Update the pc-client-linux.sh file to reflect the current
# location the script is in.
sed -i -e 's/`dirname $0`/\/opt\/papercut/g' /opt/papercut/pc-client-linux.sh

# Change ownership of copied directory and subfiles to papercut.
echo "Changing ownership of copied files to papercut."
chown -R papercut:papercut /opt/papercut

# Change file permissions for /opt/papercut and subfiles and directories.
echo "Changing permissions to 755 for /opt/papercut"
chmod -R 755 /opt/papercut

# Create symbolic link within /usr/bin for starting papercut.
ln -s /opt/papercut/pc-client-linux.sh /usr/bin/papercut
chmod 777 /usr/bin/papercut

# Tell user that papercut has been successfully installed and how to use it.
echo "Papercut was successfuly installed."
echo "To use Papercut, simply type /usr/bin/papercut into a terminal."
